apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nim-app-gitops
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: 'https://github.com/mateobuscarons/nim-app'
    targetRevision: main
    path: deploy
    directory:
      # Exclude config_map.yaml and secret.yaml from being processed by Argo CD
      exclude: '{config_map.yaml,secret.yaml}'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: nim-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
