apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  namespace: demo-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
        - name: demo-app
          image: image-registry.openshift-image-registry.svc:5000/demo-project/demo-app:latest
          ports:
            - containerPort: 8080
          env:
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: demo-app-secrets
                  key: api-key
            - name: API_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: demo-app-config
                  key: API_BASE_URL
            - name: MODEL_NAME
              valueFrom:
                configMapKeyRef:
                  name: demo-app-config
                  key: MODEL_NAME
