apiVersion: apps/v1
kind: Deployment
metadata:
  name: nim-app
  namespace: nim-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nim-app
  template:
    metadata:
      labels:
        app: nim-app
    spec:
      containers:
        - name: nim-app
          image: quay.io/pbuscaronskrieger/nim-app:0.0.13
          ports:
            - containerPort: 8080
          env:
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: nim-app-secrets
                  key: api-key
            - name: API_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: nim-app-config
                  key: API_BASE_URL
            - name: MODEL_NAME
              valueFrom:
                configMapKeyRef:
                  name: nim-app-config
                  key: MODEL_NAME
