apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: demo-app
  namespace: demo-project
spec:
  to:
    kind: Service
    name: demo-app
  port:
    targetPort: 8080
  tls:
    termination: edge
